# Site Definitions
title: 'Echo'
url: 'http://echo.dev' # the base hostname & protocol for your site, e.g. http://example.com
basecss: '' # link to base site css

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - gulpfile.js

collections:
  echo-inline:
    output: false
  echo-block:
    output: false
  echo-layout:
    output: false
  echo-components:
    output: false

echo-colors:
  -
    name: '$echo-brand-color'
    hex: '#D84315'
  -
    name: '$echo-black'
    hex: '#212121'
  -
    name: '$echo-white'
    hex: '#FFFFFF'
  -
    name: '$echo-background-dark'
    hex: '#263238'
  -
    name: '$echo-text-color'
    hex: '#616161'
  -
    name: '$echo-text-highlight-color'
    hex: '#D84315'
  -
    name: '$echo-border-color'
    hex: '#BDBDBD'

