# Site Definitions
title: 'Echo'
tagline: 'Style Sherpa'
url: 'http://echo.dev' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - gulpfile.js

collections:
  echo-typography:
    output: false
  echo-images:
    output: false
  echo-modules:
    output: false
  echo-components:
    output: false

echo-colors:
  -
    name: '$echo-brand-color'
    hex: '#D84315'
  -
    name: '$echo-black'
    hex: '#212121'
  -
    name: '$echo-white'
    hex: '#FFFFFF'
  -
    name: '$echo-background-dark'
    hex: '#263238'
  -
    name: '$echo-text-color'
    hex: '#616161'
  -
    name: '$echo-text-alt-color'
    hex: '#D84315'
  -
    name: '$echo-border-color'
    hex: '#BDBDBD'

echo-about: false